### ISSUE TITLE
Add generic label to identify objects created by Stackable

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#188]
See follow-up issue: https://github.com/stackabletech/issues/issues/503

Currently we do not have a way of identifying all Stackable objects that were created in the api-server.

We should add a single label with a known value like "vendor=stackable" or something similar that would allow easily auditing the objects created across our entire plattform.

```[tasklist]
### Prerequisites
- [ ] https://github.com/stackabletech/documentation/pull/443
- [ ] https://github.com/stackabletech/operator-rs/pull/684
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/134
- [ ] https://github.com/stackabletech/operator-rs/pull/723
- [ ] https://github.com/stackabletech/operator-rs/pull/734
```

```[tasklist]
### Label Templated files
- [ ] https://github.com/stackabletech/issues/issues/501
- [ ] https://github.com/stackabletech/demos/pull/9
- [ ] https://github.com/stackabletech/issues/issues/513
```

stackablectl will not support handing over a values.yml to Helm. if you want one, use Helm.

```[tasklist]
### Label resources deployed by the operators
- [ ] https://github.com/stackabletech/operator-rs/pull/728
- [ ] Bump `operator-rs` in operators to get the vendor label (optional, will happen anyway)
```

```[tasklist]
### Docs
- [ ] https://github.com/stackabletech/documentation/pull/540
- [ ] https://github.com/stackabletech/documentation/pull/542
```

**Comment by lfrancke** [comment]
This also goes for the CRDs itself if possible.

**Comment by soenkeliebau** [comment]
https://github.com/stackabletech/documentation/pull/443

**Comment by fhennig** [comment]
@soenkeliebau maybe but this on the list as well? https://github.com/stackabletech/issues/issues/185

**Comment by lfrancke** [comment]
Does that belong to this issue or would that be a separate one?
@Techassi how easy would you estimate #185 to be once all the other work in this issue has been done.

Personally I have a feeling that the issue seems suspiciously easy but has the chance of ending up in a lot of bikeshedding.

**Comment by Techassi** [comment]
Yes, ideally this is part of this epic. But labeling _ALL_ the things is not trivial.

We eventually aim to add labels to all of our resources, like dynamic objects, demo/stack manifests, operators and the resources they deploy.

**Comment by fhennig** [comment]
Meeting notes:

- Close https://github.com/stackabletech/stackable-cockpit/pull/186 that pull values.yaml and parses it
Close https://github.com/stackabletech/demos/pull/9 because if requires maintenance effort and will be set by stackablectl - anyways
    - We still need labels on the nested/"hidden" stuff, such as the create-spark-job creating the SparkApplication
    - We still want the labels on the third party helm charts
- Remove https://github.com/stackabletech/operator-rs/blob/d988822e7af3d363d52fb35643f0c6ed933f340a/src/helm/mod.rs#L24 because secret-op and listener-op don't have a top level resources field
- Add stackable.tech/vendor: Stackable to values.yaml in all operators e.g. https://github.com/stackabletech/trino-operator/blob/81d2de5930e1e7c7cbed205d700e956699b2f50e/deploy/helm/trino-operator/values.yaml#L23
- https://github.com/stackabletech/stackable-cockpit/blob/645a115211305cfefcf0c5ac16b8314bee35ce3b/rust/stackable-cockpit/src/utils/k8s/client.rs#L104 is still fine
- Documentation in https://docs.stackable.tech/home/nightly/concepts/labels needs to be adapted to reflect changes

**Comment by sbernauer** [comment]
I just wanted to mention that I noticed we are missing the labels on
* PVCs created by ephemeral volumes (such as datanode listeners). I fear the only way of fixing this is by putting them on the Statefulset `spec.template.spec.volumes[_].ephemeral.volumeClaimTemplate.metadata.lables` [here](https://github.com/stackabletech/operator-rs/blob/e7eb39524dcbe1308410f6b81bada5553a6b157b/src/builder/pod/volume.rs#L495). PVCs created by StatefulSet `spec.volumeClaimTemplates` (such as data or persistent listener volumes) seem to be fine
* Listener objects. When all PVCs will have proper labels this is an easy fix in https://github.com/stackabletech/listener-operator/pull/158
* Services created by listener-op

IMHO we must add those missing labels at lease to the Listener objects, as we need them for `stackablectl stacklet list` (which is currently not showing the HDFS endpoints)
