### ISSUE TITLE
Decide about log agent architecture

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#259]
This is part of this epic: https://github.com/stackabletech/issues/issues/202

Vector and fluentd support running as an Agent (Daemon, Sidecar) or an extra aggregator. What are the pros and cons? Do we want to decide on one, or is it possible to support different topologies, do we want that?

Sidecar: The product operator has to configure that

Daemon: Who sets this up? The user? Do we write an operator for that?

This is done when:
- [ ] there is a document discussing the pros and cons of each possible solution

**Comment by siegfriedweber** [comment]
We decided in a meeting on 2022-10-05 to implement the following in the first iteration:

* The products write their logs to stdout in plain text because these logs should be easily human-readable.
* Additionally the logs are written to JSON or XML files in /var/log. This should easily work for Java-based products. For other products, we will hopefully find a solution.
* The log files use a common structure to reduce the necessary transformation steps in Vector and to ease the usage of a custom logging solution using these files.
* Vector agents will be deployed as side-car containers because a daemon-set cannot (easily) read the log files.
* The Vector agents allow only Vector aggregators as a sink because we do not know yet the long-term solution and do not want to change a large amount of code in all operators in each iteration step. There is no discovery mechanism for log sinks yet, so just the endpoint of the Vector aggregator is provided.
* OpenSearch and OpenSearch Dashboards are deployed with the official Helm charts.

**Comment by lfrancke** [comment]
To add a couple of points:

- We will develop and ship a default log4j.properties file (the same for Python or other logging systems), not to add any specific features but to have some consistency, they will still look different between products because some will filter things and others have multiple files etc.
- We allow configuring log levels in the CRs (https://github.com/stackabletech/issues/issues/261)
- Talk about how to add "better" logging to our own operators
- The Vector aggregators can be configured using CRDs to point at sinks

**Comment by lfrancke** [comment]
Refinement note: This ticket might already be done.
It might make sense to present our results and decisions to the team once and then close it.
If you think something is missing then please add the open questions in the ticket

**Comment by lfrancke** [comment]
I talked to Sönke and we decided that it makes sense to write down our decisions in an ADR.
This is independent from the concrete CRD design which is part of #261

**Comment by soenkeliebau** [comment]
I am happy for the ADR to be written as a result of #261 - will close this one
