### ISSUE TITLE
Investigate whether it is possible to have a kubelet and an agent on the same "physical" machine

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#42]
We'd like to run mixed workloads if possible ("systemd" and containers).
For this we'd need to run an Agent and a Kubelet on the same node.

I'm not sure if this is possible because they both might create the same Node object?

I believe we had an issue about this at some point already but I can't find it anymore.

**Comment by Jimvin** [comment]
There are proxies for most K8s services, but I've not seen a kubelet proxy. If we had this the kubelet could we run on localhost and the agent could proxy to it for container deployments?

**Comment by siegfriedweber** [comment]
Node names must be unique. The kubelet and the agent use the hostname by default. So it is not possible to run both on the same machine without further configuration.

The name of the kubelet can be set with the `--hostname-override` option. The name of the agent node can be set with the `--hostname` option.

I am not sure if the node names must be resolvable. The [Kubernetes documentation](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) states: "consult cloud provider documentation to determine if and how the hostname is used".

I tested a different hostname for the agent on my local (real) Kubernetes installation and it worked out of the box. The following must be taken into account:
- When the hostname of the agent is changed then its certificate must be re-created. If an alternate name is used, like the fully qualified domain name or `localhost`, then the certificate can be re-used.
- The `nodeSelector` must be set accordingly, otherwise the Stackable pods can be scheduled on the kubelet. Setting the tolerations only is not sufficient.
  ```
  nodeSelector:
    kubernetes.io/arch: stackable-linux
  tolerations:
    - key: kubernetes.io/arch
      operator: Equal
      value: stackable-linux
  ```

**Comment by soenkeliebau** [comment]
I think for all intents and purposes we can pretty much sum this up as "not possible at the moment".

I'll leave this open for Lars to decide how to proceed as it was initially his ticket.

**Comment by lfrancke** [comment]
Thank you @siegfriedweber
That's very thorough research!

It's very unfortunate.....maybe at some point we should reach out to the community or revive the idea of a CRI proxy
